stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - pip install -r requirements.txt
    - python3 manage.py migrate
    - python3 manage.py collectstatic --noinput
    - python3 manage.py test
    - python3 manage.py compress --force
    - python3 manage.py collectstatic --noinput
    - python3 manage.py migrate
    - python3 manage.py runserver &
    - sleep 5
    - python3 manage.py test
  only:
    - main
