# Generated by Django 3.0.8 on 2023-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
