# Generated by Django 3.0.8 on 2023-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_profile', '0002_auto_20231203_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
